using IdentityUoW.Api.Common.Domains;
using Microsoft.AspNetCore.Identity;

namespace IdentityUoW.Api.Entities;

public class UserEntity : IdentityUser<Guid>, IDateTracking
{
    public UserEntity()
    {
        // Generated by the application (time-ordered UUIDv7), so the id is known before SaveChanges.
        Id = Guid.CreateVersion7();
    }

    public string? FullName { get; set; }

    public bool IsActive { get; set; } = true;

    public DateTimeOffset CreatedDate { get; set; }

    public DateTimeOffset? LastModifiedDate { get; set; }
}
